### ISSUE TITLE
Can't login with a Googel account

### ISSUE THREAD

**Issue by 72Joe72** [AlexCSDev/PatreonDownloader#102]
I use a Googel account on Patreon. If i try to login whit googel, he say:

Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by AlexCSDev** [comment]
Seems like google is purposely blocking their authentication stuff in automated browsers like the one used in PatreonDownloader.

I will need to think how to handle this properly.

**Comment by Cornoualis** [comment]
@72Joe72  You can log in your Patreon account from a non automated user with Google, and then go in your Patreon account settings, and set a new password.
It will allow you to connect with an email (your gmail address), instead of logging with Google. It worked for me! ;-)

**Comment by 72Joe72** [comment]
Yes it worked, thank you very much
