### ISSUE TITLE
Nothing Happens after build in Visual Studio

### ISSUE THREAD

**Issue by nsomniak6** [AlexCSDev/PatreonDownloader#104]
After the build in Visual Studios, I go to where the manual directed me: PatreonDownloader.app->bin->debug->net5.0->PatreonDownloader.app.exe. It starts to run once in a cmd screen and then disappears and nothing happens afterward. Since I am a complete novice, I don't know where to go from here. ANy suggestions would be greatly appreciated.

![Screenshot 2021-11-16 234153](https://user-images.githubusercontent.com/91837655/142136087-9e049770-2baf-4181-9de6-327c7ab0b1f0.png)

**Comment by AlexCSDev** [comment]
There is no graphical user interface. Refer to readme for more information.
