### ISSUE TITLE
Error status code Forbidden

### ISSUE THREAD

**Issue by JuIez** [AlexCSDev/PatreonDownloader#111]
Hey Guys,
I really don't know what is wrong with this, I just used it to townload something else and it worked without a problem.
![image](https://user-images.githubusercontent.com/44580956/159959884-06bc45a8-cfcd-40ed-b3ac-a4027621301d.png)

Furthermore, I never had an F Drive so I'm really confused - if anyone could help me it would be great :)
~ Julez

**Comment by AlexCSDev** [comment]
Closed #110
