### ISSUE TITLE
Same filenames

### ISSUE THREAD

**Issue by kervala** [AlexCSDev/PatreonDownloader#12]
Hi,

First, thanks a lot for this application, it's very useful :)

Unfortunately, I noticed some issue with medias with no name or the same name. I have several creators I'm supporting who post several images in the same post and all of them have the same name "1.jpg". PatreonDownloader only keeps one version of them and doesn't rename it, so if there are 10 images with the same name in the same post, there will be only one 1.jpg :(

Please could you add a fix for it ? Perhaps just checking if the file is already present and adding a suffix.

Thanks :)

If I have a little time, I'll check your code to see if I can fix the issue myself :)

**Comment by kervala** [comment]
I just created a pull request with a fix :)

#13

**Comment by AlexCSDev** [comment]
Thanks for your pull request, we'll continue discussion over there then.

**Comment by AlexCSDev** [comment]
I have created "unnamed_files_fix" branch with the code which should append a sequential number to file if file with the same name was downloaded before. The only downside is that renaming might not be consistent between different PatreonDownloader runs, but I don't think I can do anything with it. Things should be fine as long as creator does not add new files to the posts you have already downloaded or if you remove download directory on every run.

Can you test that branch? I don't have any subscriptions which include files without names, so I was only able to test it using unit testing.

**Comment by AlexCSDev** [comment]
Actually you know what, give me some time, I'll replace number with media id so we don't have any inconsistencies between runs

**Comment by AlexCSDev** [comment]
Alright, media id will now be appended to patreon files and sequential number will be appended to external files.

Please test and let me know if it works fine.

**Comment by kervala** [comment]
Thank you so much for your changes, I was really busy by my job these last days and even today since I have to migrate a server to another :(

I'll test your branch today :)

**Comment by kervala** [comment]
I'm still downloading files of my creator and duplicate filenames have a different name now, that's perfect, thank you so much and great job :)

**Comment by AlexCSDev** [comment]
Alright, that's good. Thanks for testing.

I'll do some additional changes and release a new version once I'm done.

**Comment by AlexCSDev** [comment]
Alright, I have posted version 0.9.2 which includes fix for this.

Thanks again!

**Comment by kervala** [comment]
Thanks to you and you're welcome :)
