### ISSUE TITLE
Current user cannot view this post. even If I can

### ISSUE THREAD

**Issue by LakesideMiners** [AlexCSDev/PatreonDownloader#124]
```
2022-05-06 15:56:39.6997 INFO -> postidhere
2022-05-06 15:56:39.6997 WARN Current user cannot view this post
```
I keep getting this error, however when I go to the posts page in my browser. 
https://www.patreon.com/posts/postidhere 
it loads up just fine for me
(replaced the id with ```postidhere``` as its NSFW and I don't want to show what im reading here)

**Comment by AlexCSDev** [comment]
That really doesn't tell me a lot.

Please run app with "--json" command line option and send generated .json files (you can find them in the download folder) to [alexcsdev@protonmail.com](mailto:alexcsdev@protonmail.com)

**Comment by ReysukeBaka** [comment]
No but i can send you mine rn, have multiple creators that do it

**Comment by ReysukeBaka** [comment]
email is out, hope it helps

**Comment by AlexCSDev** [comment]
Hm... seems like there is some kind of an issue with login. "current_user_can_view" is false for all posts which usually means that you are not logged in or trying to download creator you are not subscribed to. Try deleting **chromedata** folder and logging in again.

**Comment by ReysukeBaka** [comment]
Its fixed
No Longer showing the "Error"
Downloading fine now
Thanks <3

**Comment by AlexCSDev** [comment]
Great! I'll consider this closed for now
