### ISSUE TITLE
Does not pass: INFO Preparing to download...

### ISSUE THREAD

**Issue by SubbyDew** [AlexCSDev/PatreonDownloader#127]
Was having the error from issue #125 Fatal Error : BadRequest. But now having a new problem.

I've also used the test debug build from issue #125 Fatal Error : BadRequest, which gives this debug message:

`<html><head><title>patreon.com</title><script src="/cdn-cgi/apps/head/7F2Ggij0e_TCnVgy3dJ0eOuIIUs.js"></script><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={'cid':'AHrlqAAAAAMAk4NSLASErU4AtJY9og==','hsh':'DAA83DD4A3D06098A6A2CE2AD90A76','t':'bv','s':37896,'e':'839517161b8ef24994a9b92a45b36199cef605d1eb23405b376814e98b92904b','host':'geo.captcha-delivery.com'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>`

**Comment by AlexCSDev** [comment]
Please try version 0.10.3.0. I have improved browser mimicking in that version.
