### ISSUE TITLE
Warn url is blacklist even though I can view the post in my chrome

### ISSUE THREAD

**Issue by davey3223** [AlexCSDev/PatreonDownloader#131]
Hey, great app. I was able to download a bunch of some creators' posts. Sadly I am unsure if it's getting all of them. I feel like for a few I should have way more downloads/ files but that's not why I am here. I'm here because when downloading I got  `2022-06-18 12:12:54.4363 WARN Url is blacklisted: https://www.patreon.com/posts/22378242` even though I am able to view it in my own browser. On top of that, I got a lot of `Warn users who cannot view this post` even though I can. No idea how to fix either problem  Any help would be appreciated 
<img width="683" alt="Screenshot 2022-06-18 121934" src="https://user-images.githubusercontent.com/77022923/174447534-5f0235c3-c9fc-4263-b127-334dc7b4cd31.png">

**Comment by davey3223** [comment]
> As for the `user cannot view this post` issue - please try latest test build from #125.

Thanks for the reply. Good to know I can ignore the 1st part. As for the second part about using the test build from #125 I was looking at that but unsure how to incorporate it into the main build. A quick small tutorial on how to add test builds into the main build would be appreciated. Unless I just download it and use and I am overthinking it.

Thanks again for all the help and a big thanks for this awesome tool.

**Comment by AlexCSDev** [comment]
Test build is completely standalone, extract it into a separate folder and use it the same way you would use the regular one. If you want to replace the regular build with it remove everything but `.local-chromium`, `chromedata`, `download`, `logs`, `GoogleDriveToken` folders as well as `gd_credentials.json` and `mega_credentials.json` files.

Note: `--verbose` command line option has been replaced with `--log-level Trace`

**Comment by davey3223** [comment]
Awesome. Thank you for the help. Can't wait to get it working. Thanks a ton!
