### ISSUE TITLE
Does this support sync downloads?

### ISSUE THREAD

**Issue by crsleeth** [AlexCSDev/PatreonDownloader#140]
When this app downloads a Patreon page for content does it re-download overwriting previous downloads? Or does it only download new Patreon posts since the last time it was ran?

For example if I download all 100 episodes of a weekly podcast and then one week later run the app again does it re-download all 100 episodes or just the new one?

**Comment by AlexCSDev** [comment]
In most cases it should not re-download already existing files by default. Depending on the server where the file is hosted the check might range from file existance check to file size comparison. If remote file size is available and file size comparison fails the old file is backed up and new one is downloaded in its place.

The only time there might be issues is when creator adds additional files to already existing posts.
