### ISSUE TITLE
I can't run the executable!

### ISSUE THREAD

**Issue by xWiggle** [AlexCSDev/PatreonDownloader#148]
Hello, I tried to open the executable both on the new version and on an older one, but it doesn't work.
I use windows 11, I also tried on 10 but in vain.
How could I solve it?
![2022-11-07 12-14-12](https://user-images.githubusercontent.com/90107928/200309077-36b80a20-2006-4136-ae3f-dbed095e1a37.gif)

**Comment by AlexCSDev** [comment]
PatreonDownloader is command line application. You need to use command line (cmd, powershell) to run it properly.
