### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by mruac** [AlexCSDev/PatreonDownloader#15]
I am running `dotnet run` and ` dotnet publish -c Release -r win-x64 --self-contained -f netcoreapp3.1 -o bin\publish\net3.1-win-x64-release` in `PatreonDownloader.App` directory in powershell. None of the commands create the `bin` directory.

**Comment by AlexCSDev** [comment]
I can't help you unless you post a build log.

**Comment by mruac** [comment]
Hi, sorry about that. please see attached for piped output from cmd for the following commands: `dotnet run`, `dotnet build` and ` dotnet publish -c Release -r win-x64 --self-contained -f netcoreapp3.1 -o bin\publish\net3.1-win-x64-release`

[dotnetrun.txt](https://github.com/AlexCSDev/PatreonDownloader/files/5311996/dotnetrun.txt)
[dotnetbuild.txt](https://github.com/AlexCSDev/PatreonDownloader/files/5311994/dotnetbuild.txt)
[dotnetpublish.txt](https://github.com/AlexCSDev/PatreonDownloader/files/5311995/dotnetpublish.txt)

**Comment by AlexCSDev** [comment]
It looks like you don't have .NET Core 3.1 SDK installed

**Comment by mruac** [comment]
I do, according to the `--list-sdks` and `--list-runtimes` parameters.

```
PS C:\Users\ant72\Downloads\PatreonDownloader-dev\PatreonDownloader.App> dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
PS C:\Users\ant72\Downloads\PatreonDownloader-dev\PatreonDownloader.App> dotnet --list-sdks
3.1.402 [C:\Program Files\dotnet\sdk]
```

**Comment by AlexCSDev** [comment]
Honestly, I'm not sure what is going on. For some reason it tries to use .NET framework packages instead of .NET Core. Try running **dotnet restore** before running other commands. Also make sure nuget is working correctly on your computer.

**Comment by mruac** [comment]
How would I go about making sure nuget is working correctly?
