### ISSUE TITLE
Patreon temporarily blocks ip due to download

### ISSUE THREAD

**Issue by Tester17** [AlexCSDev/PatreonDownloader#158]
**EN:**
Is it possible to add the ability to set a timeout between downloading posts or a limit on their count? In my case, patreon blocks ip as spam after a certain number of downloaded posts...

**RU:**
Можно ли добавить возможность установить таймаут между загрузкой постов или ограничение на их количество? У меня был случай, когда скачалась пара сотен картинок, а затем загрузка сломалась, потому что патреон стал совать капчу, а потом и вовсе заблочил этот ip (к счастью, не навсегда)

**Comment by AlexCSDev** [comment]
Are sure you are using latest version? I've been successfully downloading really big accounts and I haven't had any issues other than periodic captcha checks during crawling stage.

**Comment by Tester17** [comment]
The last time I downloaded a few months ago, and after the ip ban I did not use this program.  I will try the latest version and report the results.

**Comment by AlexCSDev** [comment]
Any release starting with [0.10.4.0](https://github.com/AlexCSDev/PatreonDownloader/releases/tag/0.10.4.0) should work fine. Obviously support is only provided for latest version, so you should not use the version I have linked.

I will close this issue for now.
