### ISSUE TITLE
Release 24 win build

### ISSUE THREAD

**Issue by aksskl** [AlexCSDev/PatreonDownloader#160]
The windows build of release 24 is the win build of release 23. The linux build of release 24 seems to be fine.

**Comment by AlexCSDev** [comment]
My bad, wrong folder was packaged. I have replaced archive on the release page with proper one

**Comment by aksskl** [comment]
Tried the new win r24 build and getting I'm getting odd behavior. Input URLs are ignored and some fire emblem patreon "FxBQT_Robin (Grima)" posts are being processed. No matter what URL I specify, win release 24 processes those fireemblem robin files. Reverted back to r23 and URLs do work.

**Comment by AlexCSDev** [comment]
I have updated the archive once more, please try it. Should be ok this time.

**Comment by AimVaguely** [comment]
This problem still seems to exist on the Linux version.

**Comment by AlexCSDev** [comment]
Updated linux archive
