### ISSUE TITLE
No way to filter just for zips or pdfs?

### ISSUE THREAD

**Issue by PupperooX** [AlexCSDev/PatreonDownloader#165]
Currently it's a great tool but it's missing being able to fine tune what we download to certain filetypes.

**Comment by PupperooX** [comment]
Being able to filter for words would be great too. For instance a patreon I'm subbed to posts 3 zips in their highest tier. One called Mithril for the highest tier, then Platinum and Gold for the tiers below. Right now I have to download all three via the PatreonDownloader app because I can't selectively pick for links/ files with the word 'Mithril' in them.  It'd be a super handy addition :)

**Comment by AlexCSDev** [comment]
This pretty much expands ideas from #117, so I have quoted your messages there.
