### ISSUE TITLE
Pass cookies manually?

### ISSUE THREAD

**Issue by girlmaya** [AlexCSDev/PatreonDownloader#168]
I dont understand the need for a web browser included with the software instead of allowing the user to provide cookies manually. On slow systems loading a web browser before downloading can be very slow. Adding an option to provide a cookies.txt would help a lot

**Comment by AlexCSDev** [comment]
The cookies isn't the reason the browser is used. The reason behind it is anti-bot measures used by patreon. Namely **cloudflare bot management** and **datadome**. Web browser is required to get around those protections, including situations when they might trigger in the middle of page parsing.

Everyone knowledgable enough is more than welcome to implement browser-less solution assuming it as bullet-proof as the current one and doesn't change current user experience.
