### ISSUE TITLE
Question: Master post/page view?

### ISSUE THREAD

**Issue by ozchopps** [AlexCSDev/PatreonDownloader#169]
This is not an issue, it's just a question. I'm pulling a Patreon site with ~15 pages. Each post is saved (post #_description.html, media, etc) and there's a few page_#.json files too.

Should there a "master index" file that combines all this in a single scrollable rendered page generated, as I can't find anything (no index.html for example)?

**Comment by AlexCSDev** [comment]
The underlying library supports similar functionality, but this is not implemented in this application. Json files generated by `--json` command are mostly there for troubleshooting or usage by other programmers.
