### ISSUE TITLE
.exe keeps shutting down when opened

### ISSUE THREAD

**Issue by MichelleMegurine** [AlexCSDev/PatreonDownloader#172]
I'm very interested in this program, but everytime I unzip the files and open "PatreonDownloader.App.exe", it takes a little time to load and, inmediately when the text is finally showed, it closes. I have tried with latest version and the previous one and it's the same.

**Comment by AlexCSDev** [comment]
Been asked multiple times previously
https://github.com/AlexCSDev/PatreonDownloader/issues/148
https://github.com/AlexCSDev/PatreonDownloader/issues/103
https://github.com/AlexCSDev/PatreonDownloader/issues/104
https://github.com/AlexCSDev/PatreonDownloader/issues/75
