### ISSUE TITLE
i dont mean to bother but i cant figure out how intall it

### ISSUE THREAD

**Issue by poooooopy** [AlexCSDev/PatreonDownloader#176]
im having trouble figuring out how to intall the app i use linux im new to coding and im on chromebook lol you dont have to respond to me now because this isnt that important but im in need of help

**Comment by AlexCSDev** [comment]
Official x64 linux and windows builds are provided on the download page, you just unpack it into any folder and run.

On any other platforms (mac, arm, etc) you're on your own. Build instructions are provided in docs/BUILDING.md, but beyond that I can't provide any support.
