### ISSUE TITLE
"This browser or app may not be secure."

### ISSUE THREAD

**Issue by AelzarBay** [AlexCSDev/PatreonDownloader#178]
The chromium browser that pops up when I run the program will not let me sign into Patreon using the "Continue with Google" option. 

I use the Continue with Google sign in to log in to Patreon, so I have no actual password.

![!pdloginerror](https://user-images.githubusercontent.com/107370961/232337978-1b155f82-2aef-4ecf-a5ea-5579a0e1d65f.png)

**Comment by AlexCSDev** [comment]
You need to set a password on your account and login via email + password: #102

**Comment by AelzarBay** [comment]
Hey heyyyy I'm an idiot. Didn't even know you could do that. Thanks.
