### ISSUE TITLE
Chromium fails to login to Patreon via Gmail account

### ISSUE THREAD

**Issue by BubaVV** [AlexCSDev/PatreonDownloader#189]
Tried to download a post from Patreon, but had an issue with login. My account on Patreon uses login via Gmail. Chromium instance launched by downloader was treated as suspicious by Google, and get `This browser or app may not be secure. ` error while trying to log in. It forbids logging totally. Despite it, desktop Chromium does Patreon login successfully.

Remote browser with manually logged session might be a solution here. I tried to setup it, but failed - downloader opens own instance of Chromium even with passed valid `--remote-browser-address`. Tried both Chromium and Chrome with enabled remote debug with the same negative result.

I use Ubuntu Focal. Compiled the tool using dotnet-6.0 SDK

**Comment by AlexCSDev** [comment]
#178
