### ISSUE TITLE
Create Folder per Post

### ISSUE THREAD

**Issue by Serph91P** [AlexCSDev/PatreonDownloader#19]
Hi, @AlexCSDev 

question if it would be possible to create folder by post name and content.
So the Pictures would get kinda sortet and not just all dumped into one folder.

**Comment by AlexCSDev** [comment]
Hi. I prefer to not use post names in file/folder names due to the fact that they can be changed by the creator at any time and lead to duplicates during re-runs of the application when using the same download directory. The only proper way of implementing such functionality is using post id as folder name.

But, I don't really have free time to do this right now. I will be able to work on this sometime in mid-december at the earliest. If anyone is willing to implement this earlier feel free to send PR for review.

**Comment by AlexCSDev** [comment]
Unfortunately I did not have enough time to implement it in 0.9.4 so this is delayed until one of the future releases.

**Comment by mcman1987** [comment]
Would still be grateful if this was made possible. Thank you.

**Comment by JessiAuro** [comment]
The output being one giant blob of IDs makes it pretty hard to make use of this utility for me, as I usually want my archives to be chronologically sorted and have human-readable names. Having some kind of `--post-folder` flag would be really nice, even if was only the post ID.

You should be able to have both human-readable names and avoid duplicates, it's just going to be a matter of how much work you want to do to make it happen.

The ideal (but most labor-intensive) option would be to keep a database in the download directory that would map individual assets to a post ID. Basically, a more fleshed-out version of what youtube-dl does. You could either use SQLite directly or EntityFramework without too much trouble.

The easier-to-implement version would be to have a machine-readable section at the beginning of the file (or directory) name and a human-readable section at the end. On subsequent reruns you just parse out the post ID any any other info you need from the beginning of the file name. This would be considerably slower than using a proper database, but likely acceptable for how much easier it would be to implement.

My personal ideal version of this would also include a UTC timestamp of the post's creation date at the very beginning of the filename (as part of the machine-readable section) so the files are ordered chronologically when sorted alphabetically. This preserves the order of the posts so it's much easier to browse or compare your archive to posts on the site. Maybe this could be enabled with a `--timestamps` flag?

Once this is implemented, it would also let you implement some kind of output template (again like youtube-dl) which would let the user specify whatever metadata they wanted in the filenames.

**Comment by AlexCSDev** [comment]
Implemented by @JDR-Ninja in 0.10.1.

Please create new issues for suggestions not strictly related to creating a new folder per post, thank you!
