### ISSUE TITLE
[Question] As of right now, is it working?

### ISSUE THREAD

**Issue by Right-BuggerOff** [AlexCSDev/PatreonDownloader#190]
I want to make sure before I pay for a Patreon creator.

**Comment by AlexCSDev** [comment]
Should be working absolutely fine

**Comment by Right-BuggerOff** [comment]
Duh. That's why you're supposed to fix it when it breaks.

**Comment by Masamune3210** [comment]
Maybe.....don't be rude to the person who makes the software you are wanting to use?

**Comment by Right-BuggerOff** [comment]
No. You make shit, it breaks, I let you know, you go "UUUUM. UUUUUUM. UUUM. iT sHoUlD bE wOrkIng" of course it isn't you fucking moron.

And man, whose heav’n-erected face,
⁠The smiles of love adorn,
Man’s inhumanity to Man,
⁠Makes countless thousands mourn.
– Robert Burns

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
