### ISSUE TITLE
Chrome Page issue 

### ISSUE THREAD

**Issue by Bo0omShakalaka** [AlexCSDev/PatreonDownloader#206]
After I put my Gmail account it keeps showing me that is incorrect.
 
![Error](https://github.com/AlexCSDev/PatreonDownloader/assets/61621931/7eb063b2-d4c0-4d3a-851e-3106c9226cd6)

What should I do?

**Comment by Bo0omShakalaka** [comment]
![Capture](https://github.com/AlexCSDev/PatreonDownloader/assets/61621931/bd0ec61a-ee53-4651-a8a3-b9e35a168c6c)

**Comment by AlexCSDev** [comment]
Google logins are not supported. Create a password in your account settings and login using your email address.
