### ISSUE TITLE
Downloaded Images Display Artifacts

### ISSUE THREAD

**Issue by chadfrank74** [AlexCSDev/PatreonDownloader#208]
Hello, thanks for this much needed tool. I noticed that the images it downloads, however, are not identical to downloading manually from the browser. Additionally, the files downloaded from the tool display discoloration artifacts. The image file in question is a jpg (lossy format). Is it possible the tool could be performing an additional lossy recompression on the images? If necessary I can provide an image pair example.

**Comment by AlexCSDev** [comment]
It has been previously confirmed that files downloaded manually via browser are actually the ones which are not identical to the files stored on patreon servers.

As for the discoloration thing you will need to provide an example. Will be the best if you upload the files to whatever place does not alter the images (any file hosting like mega, google drive, dropbox, mediafire, etc). PatreonDownloader does not perform any kind of modification of downloaded files, so I can only think of display color profile shenanigans right now.
