### ISSUE TITLE
User tags generating errors

### ISSUE THREAD

**Issue by Poag** [AlexCSDev/PatreonDownloader#21]
Hello, It appears any custom user tags generate errors and abort any image downloads.
With verbose logging on this is what appears for a post

> 2020-11-23 17:00:00.2282 DEBUG [83874473] Verification: Started
> 2020-11-23 17:00:00.2282 DEBUG [83874473] Is a media
> 2020-11-23 17:00:00.2282 DEBUG [83874473] Verification: OK
> 2020-11-23 17:00:00.2282 DEBUG [user_defined;3d] Verification: Started
> 2020-11-23 17:00:00.2282 ERROR Verification for user_defined;3d: Unknown type for "included": post_tag
> 2020-11-23 17:00:00.2441 ERROR Verification for user_defined;3d: Unknown type for "included": post_tag
> 2020-11-23 17:00:00.2441 DEBUG [user_defined;group] Verification: Started
> 2020-11-23 17:00:00.2441 ERROR Verification for user_defined;group: Unknown type for "included": post_tag
> 2020-11-23 17:00:00.2441 ERROR Verification for user_defined;group: Unknown type for "included": post_tag
> 2020-11-23 17:00:00.2441 DEBUG [user_defined;stereo] Verification: Started
> 2020-11-23 17:00:00.2441 ERROR Verification for user_defined;stereo: Unknown type for "included": post_tag
> 2020-11-23 17:00:00.2441 ERROR Verification for user_defined;stereo: Unknown type for "included": post_tag
> 2020-11-23 17:00:00.2441 DEBUG [user_defined;touch] Verification: Started
> 2020-11-23 17:00:00.2441 ERROR Verification for user_defined;touch: Unknown type for "included": post_tag
> 2020-11-23 17:00:00.2441 ERROR Verification for user_defined;touch: Unknown type for "included": post_tag

As the creator in question is exceedingly diligent in adding tags this means all posts downloads fail.

I left it running for about 40 mins to be sure that the attachments wouldn't download later, but ended up with a 5GB log file instead, available if needed.

**Comment by Poag** [comment]
Further update, leaving it even longer is has now started downloading images. So looks to be a processing error that does not impact the download processing.

**Comment by AlexCSDev** [comment]
Hi. This is not a critical error and indeed it does not impact download process at all. But it appears that it drops crawling performance by a lot. I think I can fix it by tweaking api requests so it ignores those tags, will you be able to upload json dumps of that creator somewhere (created via --json command line option)?

**Comment by AlexCSDev** [comment]
Should be solved in 0.9.3. You have not provided requested information, so I have no way of testing this.
