### ISSUE TITLE
Download in subfolders

### ISSUE THREAD

**Issue by breatfr** [AlexCSDev/PatreonDownloader#221]
hi,

before all thanks for this application.
is there a way to download in subfolders to keep hierarchy like this:

- patreon creator name
     -  post_title_1
          - all pics from post_tile_1
     - post_title_2
          - all pics from post_tile_2
etc

**Comment by angramainyuu** [comment]
--use-sub-directories

**Comment by breatfr** [comment]
> --use-sub-directories

thanks you very much
