### ISSUE TITLE
cant login because chromium said "This browser or app may not be secure."

### ISSUE THREAD

**Issue by t1t03l3k** [AlexCSDev/PatreonDownloader#229]

**Comment by simonbcn** [comment]
Same problem with `Patreon Downloader 27` on `Fedora Linux 40` when I try to login with Google account.
I think it would be simpler for it to open the default browser or, even faster, to access the browser's cookies by default.

**Comment by AlexCSDev** [comment]
https://github.com/AlexCSDev/PatreonDownloader/issues/178#issuecomment-1510470313
