### ISSUE TITLE
Error when attempting to download campaign content - "Unable to retrieve campaign id: Forbidden"

### ISSUE THREAD

**Issue by mathe00** [AlexCSDev/PatreonDownloader#237]
Hi there!

First of all, thank you so much for the awesome tool! I'm really loving it and appreciate all the hard work that’s gone into it.

I encountered an issue while trying to download content from a specific Patreon campaign. Here's the command I ran:

```bash
./PatreonDownloader.App --url https://www.patreon.com/c/creator --download-directory /home/me/Download/creator/ --descriptions --embeds --campaign-images --json --use-sub-directories --sub-directory-pattern "[%PostId%] %PublishedAt% %PostTitle%" --max-sub-directory-name-length 100 --filenames-fallback-to-content-type --log-save --file-exists-action KeepExisting
```

I get the following error:

```
2024-10-24 15:22:52.9591 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve campaign id: Error status code returned: Forbidden
 ---> UniversalDownloaderPlatform.Common.Exceptions.DownloadException: Error status code returned: Forbidden
```

It seems like the app is unable to retrieve the campaign ID and hits a "Forbidden" error. I'm not sure if this is an issue with how I’m running the command, or if it’s more of a permissions/authentication issue related to the Patreon API. Perhaps it could also benefit from a clearer error message or a more descriptive warning.

I apologize if this is a duplicate issue! Feel free to close it if it’s already been reported, just mention the original issue if possible. 😅

In case it helps, I'm happy to answer any questions or provide more information if needed!

Thanks again, and keep up the great work! 🙏

**Comment by AlexCSDev** [comment]
Hello. Not much I can help you with I'm afraid since I am almost sure you are getting flagged by cloudflare for some reason. I can recommend using VPN or supplying a proxy server via command line arguments.

I have experienced having more issues with getting around cloudflare on linux than on windows, this seems to happen due to some differences in how network features are handled by .NET on different platforms.

**Comment by mathe00** [comment]
> Hello. Not much I can help you with I'm afraid since I am almost sure you are getting flagged by cloudflare for some reason. I can recommend using VPN or supplying a proxy server via command line arguments.
> 
> I have experienced having more issues with getting around cloudflare on linux than on windows, this seems to happen due to some differences in how network features are handled by .NET on different platforms.

Oh, I see! I'm using a VPN on Linux, which I think explains the problem. I get dozens of Cloudflare “CAPTCHAs” a day (I can't take it anymore). So I think that's where it's coming from. But I'm still able to log into my account, it's weird... Anyway, thanks for your message and good luck then.

**Comment by mathe00** [comment]
(close the exit if you like, I'll leave you to it)

**Comment by AlexCSDev** [comment]
Yea, if you're getting a lot of cloudflare captchas with your VPN that will be the reason.
