### ISSUE TITLE
need to trim creator's name folder

### ISSUE THREAD

**Issue by sitex** [AlexCSDev/PatreonDownloader#24]
Hello.

First of all, thanks for the amazing software!

I found this bug on Windows using this command:
```
PatreonDownloader.App.exe --url https://www.patreon.com/user/posts?u=9011118
```

Than application tries to write content to the default folder ```download\<user_name>```. But in this case the <user_name> contains a trailing space and looks like this "ducky 3d ". Looks like Windows doesn't like trailing spaces in a path. So it couldn't write files to the default folder.

Yes, I fixed that using "--download-directory"

**Comment by AlexCSDev** [comment]
Hi. Thank for for your kind words.

Please try using release 0.9.3.1 and let me know if it fixes this issue.

**Comment by sitex** [comment]
I've just tested! All good!

**Comment by AlexCSDev** [comment]
Great, thanks!
