### ISSUE TITLE
I can't log in with google

### ISSUE THREAD

**Issue by Bagener** [AlexCSDev/PatreonDownloader#243]
The buttom can't be push, I don't have i device so I can't log in with apple, and my facebook is dead...
![image](https://github.com/user-attachments/assets/fb4c455d-04c0-4a3a-8725-523724dbdfe8)

**Comment by AlexCSDev** [comment]
https://github.com/AlexCSDev/PatreonDownloader/issues/178#issuecomment-1510470313
