### ISSUE TITLE
Difference in file size

### ISSUE THREAD

**Issue by LipeCavera** [AlexCSDev/PatreonDownloader#57]
Hi. I ran some tests. I compared the file downloaded by the app with the "save as" of the browser.

The dimensions of the photos are ok. I noticed a sudden difference in the file size.

Example.
Save as File: 600kb
App file: 200kb.

Is that so?

![filecomparasion](https://user-images.githubusercontent.com/83845400/118050912-87b0c380-b356-11eb-9cf2-28052c1c3282.jpg)

**Comment by AlexCSDev** [comment]
I'm afraid I can't really say why this is happening without additional information. Please send json dumps (created with --json parameter) as well as both files and url of the post in question to alexcsdev@protonmail.com

**Comment by AlexCSDev** [comment]
I am closing this as I have not received any response.
