### ISSUE TITLE
Can't download profiles with new version

### ISSUE THREAD

**Issue by Liz-chan** [AlexCSDev/PatreonDownloader#61]
It was working before, but with 0.10 I get
`FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Common.Exceptions.UniversalDownloaderException: Unable to retrieve campaign id: Unable to retrieve data from https://www.patreon.com/***/posts: Error status code returned: Forbidden`

**Comment by AlexCSDev** [comment]
Have you tried removing **.local-chromium** and **chromedata** folders?

**Comment by Liz-chan** [comment]
Yep I deleted them and logged in again, but I'm still getting the error

**Comment by AlexCSDev** [comment]
Are you on linux? I've been able to replicate this on linux, but not on windows

**Comment by Liz-chan** [comment]
Nope I'm on Windows 10, version 1809 to be exact.

**Comment by AlexCSDev** [comment]
I think cloudflare does not like user-agent. Can you post it so I can test this theory?

Launch .local-chromium\.....\chrome-win\chrome.exe, open https://www.whatismybrowser.com/detect/what-is-my-user-agent and post the result here.

**Comment by Liz-chan** [comment]
The user-agent is 
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.0 Safari/537.36`

**Comment by AlexCSDev** [comment]
Can you run it with --verbose parameter and post the full log of that run here?

**Comment by Liz-chan** [comment]
Sure, here it is
[2021-06-13.log](https://github.com/AlexCSDev/PatreonDownloader/files/6644283/2021-06-13.log)

**Comment by AlexCSDev** [comment]
Alright, thanks. I can't say I have any ideas about what might be wrong, but I'll try to figure it out.

**Comment by Liz-chan** [comment]
Using Patreon inside the browser inside .local-chromium works fine, just doesn't work with the downloader.

**Comment by AlexCSDev** [comment]
Yea, it's some kind of an issue with the requests made by the app itself as it is no longer relies on the browser for anything past login stage. Maybe your ip address is flagged by cloudflare and their bot management platform performs more strict checks than usual. I'll try to modify the requests to behave more like a regular browser and post a test build here later today.

**Comment by AlexCSDev** [comment]
Alright, I think I have figured it out.

It seems like Windows 10 1809 does not support TLS 1.3. This triggers cloudflare's bot protection.

I will do some more research tomorrow, but it seems like I will probably not be able to fix this and your only option will be to either keep using 0.9 or upgrade your windows to more recent version.

**Comment by Liz-chan** [comment]
Oh yeah it seems you're right, 1903 was the one that added native TLS 1.3. The only reason I'm still on 1809 is because I use LTSC, but thankfully a new version of it is coming out in the second half of this year so if 0.9 works until then then it's alright.

**Comment by AlexCSDev** [comment]
Did some research: TLS 1.3 and HTTP2 are required in order to not trigger cloudflare bot protection. The readme file will be updated to reflect new minimal OS version requirements.
