### ISSUE TITLE
FATAL Fatal Error, application will be closed: System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by Masamune3210** [AlexCSDev/PatreonDownloader#66]
Getting a DirectoryNotFoundException whenever I try to download any Patreon with a space in their name, possibly not quoting the path passed to something? 

Also, it seems the --download-directory flag isn't working as no matter where I point it, the files always end up in a download folder inside the apps directory

**Comment by Masamune3210** [comment]
This was seemingly introduced in 0.10,  as 0.9.4.2 is working just fine with the space in the name and the directory flag is being respected correctly

**Comment by AlexCSDev** [comment]
--download-directory not working has been fixed in 0.10.0.1, not sure if I understand the part about the space, do you have an example?

**Comment by Masamune3210** [comment]
not sure, as I recently purged a bunch of my patreons since I had money issues, but it was basically any Patreon which had a space in its name, iirc it would succeed to make the folder, but fail when trying to do anything with it with a filenotfound

**Comment by Masamune3210** [comment]
Could be talking out my arse on this one honestly since its been so long I don't really remember it. feel free to ignore it if you cant repro sorry

**Comment by AlexCSDev** [comment]
Alright, I'll close this for now as I don't have any issues with creators who have spaces in their name.
