### ISSUE TITLE
Issues running PatreonDownloader on Windows 10

### ISSUE THREAD

**Issue by dancazcu90** [AlexCSDev/PatreonDownloader#70]
Hello,

When i try to run the code i get the following error:

==========================================================================
C:\Users\Ryzen\Downloads\PatreonDownloader-dev\PatreonDownloader.App>dotnet build -c release
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  UniversalDownloaderPlatform.Common -> C:\Users\Ryzen\Downloads\PatreonDownloader-dev\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Common\bin\release\net5.0\UniversalDownloaderPlatform.Common.dll
  PatreonDownloader.Common -> C:\Users\Ryzen\Downloads\PatreonDownloader-dev\PatreonDownloader.Common\bin\release\net5.0\PatreonDownloader.Common.dll
  UniversalDownloaderPlatform.DefaultImplementations -> C:\Users\Ryzen\Downloads\PatreonDownloader-dev\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\bin\release\net5.0\UniversalDownloaderPlatform.DefaultImplementations.dll
  PatreonDownloader.PuppeteerEngine -> C:\Users\Ryzen\Downloads\PatreonDownloader-dev\PatreonDownloader.PuppeteerEngine\bin\release\net5.0\PatreonDownloader.PuppeteerEngine.dll
  UniversalDownloaderPlatform.Engine -> C:\Users\Ryzen\Downloads\PatreonDownloader-dev\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\bin\release\net5.0\UniversalDownloaderPlatform.Engine.dll
C:\Users\Ryzen\Downloads\PatreonDownloader-dev\PatreonDownloader.Implementation\PatreonCrawledUrlProcessor.cs(16,40): error CS0738: 'PatreonCrawledUrlProcessor' does not implement interface member 'ICrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)'. 'PatreonCrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)' cannot implement 'ICrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)' because it does not have the matching return type of 'Task<bool>'. [C:\Users\Ryzen\Downloads\PatreonDownloader-dev\PatreonDownloader.Implementation\PatreonDownloader.Implementation.csproj]

Build FAILED.

C:\Users\Ryzen\Downloads\PatreonDownloader-dev\PatreonDownloader.Implementation\PatreonCrawledUrlProcessor.cs(16,40): error CS0738: 'PatreonCrawledUrlProcessor' does not implement interface member 'ICrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)'. 'PatreonCrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)' cannot implement 'ICrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)' because it does not have the matching return type of 'Task<bool>'. [C:\Users\Ryzen\Downloads\PatreonDownloader-dev\PatreonDownloader.Implementation\PatreonDownloader.Implementation.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.87

============================================================================

Maybe i'm missing something? Could you support please?

Thanks!

**Comment by AlexCSDev** [comment]
**MSBUILD : error MSB1001: Unknown switch.
Switch: -verbose**

Remove -verbose from the build command.

**Comment by AlexCSDev** [comment]
There is something wrong with your copy of source code. I have compiled fresh copy of **dev** branch just fine.

**Comment by dancazcu90** [comment]
I just got another copy, with the latest submodules, but I seem to have the same issue - i used GitHub desktop this time to dld the PatreonDownloader + UniversalDownloaderPlatform which i then copied in the submodules folder  : 

C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.App>dotnet publish -c Release -r win-x64 --self-contained -f net5.0 -o bin\publish\net5.0-win-x64-release
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.Common\PatreonDownloader.Common.csproj (in 127 ms).
  Restored C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Common\UniversalDownloaderPlatform.Common.csproj (in 127 ms).
  Restored C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\UniversalDownloaderPlatform.DefaultImplementations.csproj (in 330 ms).
  Restored C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.Implementation\PatreonDownloader.Implementation.csproj (in 330 ms).
  Restored C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloaderPlatform.Engine.csproj (in 334 ms).
  Restored C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.PuppeteerEngine\PatreonDownloader.PuppeteerEngine.csproj (in 615 ms).
  Restored C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.App\PatreonDownloader.App.csproj (in 615 ms).
  PatreonDownloader.Common -> C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.Common\bin\Release\net5.0\PatreonDownloader.Common.dll
  UniversalDownloaderPlatform.Common -> C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Common\bin\Release\net5.0\UniversalDownloaderPlatform.Common.dll
  PatreonDownloader.PuppeteerEngine -> C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.PuppeteerEngine\bin\Release\net5.0\PatreonDownloader.PuppeteerEngine.dll
C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\Helpers\URLChecker.cs(15,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\UniversalDownloaderPlatform.Engine.csproj]
  UniversalDownloaderPlatform.Engine -> C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.Engine\bin\Release\net5.0\UniversalDownloaderPlatform.Engine.dll
C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\RemoteFileSizeChecker.cs(16,27): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\UniversalDownloaderPlatform.DefaultImplementations.csproj]
  UniversalDownloaderPlatform.DefaultImplementations -> C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.DefaultImplementations\bin\Release\net5.0\UniversalDownloaderPlatform.DefaultImplementations.dll
C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.Implementation\PatreonCrawledUrlProcessor.cs(16,40): error CS0738: 'PatreonCrawledUrlProcessor' does not implement interface member 'ICrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)'. 'PatreonCrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)' cannot implement 'ICrawledUrlProcessor.ProcessCrawledUrl(ICrawledUrl, string)' because it does not have the matching return type of 'Task<bool>'. [C:\Users\Ryzen\Documents\GitHub\PatreonDownloader\PatreonDownloader.Implementation\PatreonDownloader.Implementation.csproj]

**Comment by dancazcu90** [comment]
In any case i tried to run directly the release and i think there is a bug caused by the name of the Patreon Blog : 

2021-06-29 22:31:59.6151 FATAL Fatal error, application will be closed: UniversalDownloaderPlatform.Engine.Exceptions.UniversalDownloaderPlatformException: Unable to create download directory
 ---> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\Ryzen\Downloads\PatreonDownloaderApp\net5.0-win-x64-release\download\C3|Nik'

C3|Nik - contains invalid characters for Windows, can the name be changed to something generic or check/replace invalid characters?

**Comment by AlexCSDev** [comment]
> C3|Nik - contains invalid characters for Windows, can the name be changed to something generic or check/replace invalid characters?
I have created a new issue to track this: #72

Regarding your build issues - use git's built-in tools to checkout correct submodules. You should not checkout submodules separately and then place them into the expected directory.

**Comment by dancazcu90** [comment]
It worked building after fix #73 :)

**Comment by AlexCSDev** [comment]
Alright, I'm glad that it is fixed for you now.
