### ISSUE TITLE
Docs do not explain plugin building process

### ISSUE THREAD

**Issue by WindedHero** [AlexCSDev/PatreonDownloader#71]
Please add to the docs :) Had to trial-and-error, not sure if I did it right..

**Comment by AlexCSDev** [comment]
Plugins are a part of UniversalDownloaderPlatform so I made an issue in its repository: https://github.com/AlexCSDev/UniversalDownloaderPlatform/issues/2

For now you can refer to the following projects/files when developing your own plugins:
https://github.com/AlexCSDev/UniversalDownloaderPlatform/tree/master/UniversalDownloaderPlatform.GoogleDriveDownloader
https://github.com/AlexCSDev/UniversalDownloaderPlatform/tree/master/UniversalDownloaderPlatform.MegaDownloader
https://github.com/AlexCSDev/UniversalDownloaderPlatform/blob/master/UniversalDownloaderPlatform.Common/Interfaces/Plugins/IPlugin.cs

**Comment by WindedHero** [comment]
I think you misunderstand.
/Docs/Building.md mentions "after building the plugin binaries..." but does not explain that process for the uninitiated, and those plugins are included in this source so I would argue this ticket is related to this project, not the other. 

/Docs/Googledrive.md provides a rudimentary walkthrough but does not include the build process either. 

I'm not well versed in compiling apps from their source (like 98% of the internet) so I only opened this ticket to suggest to make your documentation a little more accessible.

**Comment by AlexCSDev** [comment]
The plugins are no longer part of this project starting with 0.10.0, the documentation is slightly outdated and this part will be modified in the future to reflect that.

Commands listed in docs/Building.md can also be used to build plugins. I suggest you to use pre-built binaries if the information contained in that file (including references to microsoft documentation) is not enough for you.

Any kind of improvements to build documentation are not planned right now as building any part of PatreonDownloader is no different to building any other .net application.
