### ISSUE TITLE
So how do you actually use the program?

### ISSUE THREAD

**Issue by Degen4thewin** [AlexCSDev/PatreonDownloader#75]
There is no tutorial on how to actually use the program for none coders, i have absolutely no idea what the hell anything means at all. So how do you actually use this program?

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/127051538-73345c31-6821-4128-bf7b-3328b86db2a3.png)

**Comment by Degen4thewin** [comment]
yes i already seen that "usage" section but how the hell do i input the creator url?

**Comment by Degen4thewin** [comment]
love how you double click on patreondownloader.app.exe only for it to immediately close, if your fast enough youll see an error that says theres no creator url but doesnt tell you where you input that. is it in a config file? do you have to create the file? if you do how? absolutely no instruction.

**Comment by AlexCSDev** [comment]
https://omics.pnl.gov/software/command-line-application-help
