### ISSUE TITLE
Building from Source

### ISSUE THREAD

**Issue by neabb** [AlexCSDev/PatreonDownloader#83]
Just a heads up for anybody building from source:

You have to include all of the code from the UniversalDownloaderPlatform in https://github.com/AlexCSDev/UniversalDownloaderPlatform into the 'submodules/UniversalDownloaderPlatform' folder.  

Regards,
Noah

**Comment by AlexCSDev** [comment]
You don't have to do it manually if you do **git clone --recurse-submodules**. If you already cloned repo without submodules you should use **git submodule update --init --recursive**. That's the proper way of doing that.
