### ISSUE TITLE
Unable to create an executable

### ISSUE THREAD

**Issue by BrentonFB** [AlexCSDev/PatreonDownloader#84]
Hello Everyone I have been trying to follow the Build document when following how to create an executable of the application. I am wondering if there are any visual tutorials on how to set up DotNet with the files here. I've installed Dotnet a multitude of times and have tried to create an executable with Visual Studio, the command prompt, and even trying to run the dotnet run in the application folder. 

Is there a step that I am missing maybe a file here?

**Comment by OKLMCh3v4l** [comment]
same for me

**Comment by AlexCSDev** [comment]
If you are encountering errors regarding UniversalDownloaderPlatform try checking out the source code using **git clone --recurse-submodules**. The documentation will be updated to reflect that requirement.
